version: '3.8'

services:
  node:
    container_name: bonsay_admin
    restart: always
    tty: true
    build: ./
    volumes:
      - /etc/letsencrypt/live/admin.bonsay.istmen.space/fullchain.pem:/etc/letsencrypt/live/admin.bonsay.istmen.space/fullchain.pem
      - /etc/letsencrypt/live/admin.bonsay.istmen.space/privkey.pem:/etc/letsencrypt/live/admin.bonsay.istmen.space/privkey.pem
    networks:
      - bonsay
networks:
  bonsay:
    external: true
